### ISSUE TITLE
. . . . .

### ISSUE THREAD

**Issue by jasonwynn10** [ProestCorp/ProestMine#1]
What even is this??

**Comment by TheProest35YT** [comment]
A software for mcpe

**Comment by TheProest35YT** [comment]
And Making A Web

**Comment by jasonwynn10** [comment]
can you explain in more detail?

**Comment by TheProest35YT** [comment]
Software (example : PocketMine)

Website : Download phar , Submit plugins , Homepage , Contact , Jenkins like Github Pages but  kinda xenForo thingy

**Comment by TheProest35YT** [comment]
Every HTML file is blank because I need a Design so I finding

**Comment by TheProest35YT** [comment]
If you dont get it it's ok

**Comment by jasonwynn10** [comment]
how long have you been using github?

**Comment by TheProest35YT** [comment]
Why ?

**Comment by jasonwynn10** [comment]
it doesn't appear that you know what you are doing when it comes to github pages for web development... no offense

**Comment by jasonwynn10** [comment]
also, if there aren't more people added to this organization within the next week, i'm leaving

**Comment by TheProest35YT** [comment]
You can  tell me who you want I'll invite them

**Comment by jasonwynn10** [comment]
you can find people

**Comment by TheProest35YT** [comment]
Like who most people don't wanna

**Comment by TheProest35YT** [comment]
BTW publicise your account on @ProestCorp

**Comment by TheProest35YT** [comment]
Thanks , Jason btw who deleted the index.html

**Comment by jasonwynn10** [comment]
what do you mean?

**Comment by TheProest35YT** [comment]
Who deleted the old index.html

**Comment by jasonwynn10** [comment]
its there

**Comment by TheProest35YT** [comment]
Im mean the one with only some codes not the usual one we are using now
